deployment_data=[ "deployment_id",
    "instrumentID",
    "ptt",
    "transmission_settings",
    "transmission_mode",
    "duty_cycle",
    "instrument_settings" ,
    "deployment_datetime" ,
    "deployment_latitude", 
    "deployment_longitude",
    "deployment_end_type" ,
    "detachment_datetime",
    "detachment_details" ,
    "detachment_latitude",
    "detachment_longitude",
    "track_start_time",
    "track_start_latitude",
    "track_start_longitude",
    "track_end_time",
    "track_end_latitude",
    "track_end_longitude",
    "sun_elevation_angle" ,
    "argos_filter_method" ,
    "organismid" ,
    "scientific_name" ,
    "scientific_name_source",
    "common_name" ,
    "organism_sex",
    "organism_weight_at_deployment" ,
    "organism_weight_remeasurement" ,
    "organism_weight_remeasurement_time" ,
    "organism_size" ,
    "organism_size_measurement_type",
    "organism_size_measurement_description",
    "organism_size_measurement_time",
    "organism_age_reproductive_class",
    "trapping_method_details" ,
    "attachment_method" ,
    "environmental_calibrations_done",
    "environmental_qc_done"  ,
    "environmental_qc_problems_found" ,
    "environmental_qc_notes",
    "physiological_calibrations_done" ,
    "physiological_qc_done" ,
    "physiological_qc_problems_found", 
    "physiological_qc_notes", 
    "accelerometry_position_of_accelerometer_on_organism" ,
    "accelerometry_orientation_of_accelerometer_on_organism" ,
    "accelerometry_calibrations_done" ,
    "accelerometry_qc_done" ,
    "accelerometry_qc_problems_found" ,
    "accelerometry_qc_notes" ,
    "owner_name" ,
    "owner_email_contact",
    "owner_institutional_contact",
    "owner_phone_contact",
    "license",
    "other_relevent_identifier",
    "other_datatypes_associated_with_deployment",
    "references",
    "citation"]  

device_data=[    "instrument_id" ,
    "instrument_type" ,
    "instrument_model_number"  ,
    "instrument_manufacturer" ,
    "instrument_serial_number" ,
    "horizontal_sensor_tracking_device",
    "horizontal_sensor_uplink_Interval" ,
    "horizontal_sensor_uplink_interval_units" ,
    "vertical_sensor_units_reported"  ,
    "vertical_sensor_resolution" ,
    "vertical_lower_sensor_detection_limit" ,
    "vertical_upper_sensor_detection_limit" ,
    "vertical_sensor_precision" ,
    "vertical_sensor_sampling_frequency" ,
    "vertical_sensor_duty_cycling",
    "vertical_sensor_calibration_date" ,
    "vertical_sensor_calibration_details",
    "environmental_sensor_type" ,
    "environmental_sensor_manufacturer",
    "environmental_sensor_model",
    "environmental_sensor_units_reported" ,
    "environmental_lower_sensor_detection_limit" ,
    "environmental_upper_sensor_detection_limit",
    "environmental_sensor_precision",
    "environmental_sensor_sampling_frequency" ,
    "environmental_sensor_duty_cycling" ,
    "environmental_sensor_calibration_date",
    "environmental_sensor_calibration_details" ,
    "physiological_sensor_type" ,
    "physiological_sensor_manufacturer",
    "physiological_sensor_model" ,
    "physiological_sensor_units_reported" ,
    "physiological_lower_sensor_detection_limit" ,
    "physiological_upper_sensor_detection_limit",
    "physiological_sensor_precision",
    "physiological_sensor_sampling_frequency" ,
    "physiological_sensor_duty_cycling",
    "physiological_sensor_calibration_date",
    "physiological_sensor_calibration_details" ,
    "physiological_sensor_model",
    "accelerometry_sensor_manufacturer" ,
    "accelerometry_sensor_model" ,
    "accelerometry_sensor_axes",
    "accelerometry_sensor_units_reported" ,
    "accelerometry_lower_sensor_detection_limit" ,
    "accelerometry_upper_sensor_detection_limit" ,
    "accelerometry_sensor_precision",
    "accelerometry_sensor_sampling_frequency" ,
    "accelerometry_sensor_duty_cycling" ,
    "accelerometry_sensor_calibration_date" ,
    "accelerometry_sensor_calibration_details" ]



input_data=['instrumentID','deploymentID', 'organismID', 'organismIDSource',
            'time','latitude','longitude','argosLC','argosErrorRadius','argosSemiMajor',
            'argosSemiMinor','argosOrientation','argosGDOP','gpsSatelliteCount','residualsGPS',
             'temperatureGLS','depthGLS','sensorIMeasurement','sensor_type' ]



def set_row_data(data,csv_type):
    if csv_type == 'Deployment MetaData':
        row_data=([ data.deployment_id,
                            data.instrumentID,
                            data.ptt,
                            data.transmission_settings,
                            data.transmission_mode,
                            data.duty_cycle,
                            data.instrument_settings ,
                            data.deployment_datetime ,
                            data.deployment_latitude ,
                            data.deployment_longitude,
                            data.deployment_end_type ,
                            data.detachment_datetime,
                            data.detachment_details ,
                            data.detachment_latitude,
                            data.detachment_longitude,
                            data.track_start_time,
                            data.track_start_latitude,
                            data.track_start_longitude,
                            data.track_end_time,
                            data.track_end_latitude,
                            data.track_end_longitude,
                            data.sun_elevation_angle ,
                            data.argos_filter_method ,
                            data.organismid ,
                            data.scientific_name ,
                            data.scientific_name_source,
                            data.common_name ,
                            data.organism_sex,
                            data.organism_weight_at_deployment ,
                            data.organism_weight_remeasurement ,
                            data.organism_weight_remeasurement_time ,
                            data.organism_size ,
                            data.organism_size_measurement_type,
                            data.organism_size_measurement_description,
                            data.organism_size_measurement_time,
                            data.organism_age_reproductive_class,
                            data.trapping_method_details, 
                            data.attachment_method ,
                            data.environmental_calibrations_done,
                            data.environmental_qc_done  ,
                            data.environmental_qc_problems_found ,
                            data.environmental_qc_notes,
                            data.physiological_calibrations_done ,
                            data.physiological_qc_done ,
                            data.physiological_qc_problems_found ,
                            data.physiological_qc_notes ,
                            data.accelerometry_position_of_accelerometer_on_organism ,
                            data.accelerometry_orientation_of_accelerometer_on_organism ,
                            data.accelerometry_calibrations_done ,
                            data.accelerometry_qc_done ,
                            data.accelerometry_qc_problems_found ,
                            data.accelerometry_qc_notes ,
                            data.owner_name ,
                            data.owner_email_contact,
                            data.owner_institutional_contact,
                            data.owner_phone_contact,
                            data.license,
                            data.other_relevent_identifier,
                            data.other_datatypes_associated_with_deployment,
                            data.references,
                            data.citation
                        ] )
    elif csv_type == 'Device MetaData':
                row_data=[data.instrument_id ,
                        data.instrument_type ,
                        data.instrument_model_number  ,
                        data.instrument_manufacturer ,
                        data.instrument_serial_number ,
                        data.horizontal_sensor_tracking_device,
                        data.horizontal_sensor_uplink_Interval ,
                        data.horizontal_sensor_uplink_interval_units ,
                        data.vertical_sensor_units_reported  ,
                        data.vertical_sensor_resolution ,
                        data.vertical_lower_sensor_detection_limit ,
                        data.vertical_upper_sensor_detection_limit ,
                        data.vertical_sensor_precision ,
                        data.vertical_sensor_sampling_frequency ,
                        data.vertical_sensor_duty_cycling,
                        data.vertical_sensor_calibration_date ,
                        data.vertical_sensor_calibration_details,
                        data.environmental_sensor_type ,
                        data.environmental_sensor_manufacturer,
                        data.environmental_sensor_model,
                        data.environmental_sensor_units_reported ,
                        data.environmental_lower_sensor_detection_limit ,
                        data.environmental_upper_sensor_detection_limit,
                        data.environmental_sensor_precision,
                        data.environmental_sensor_sampling_frequency ,
                        data.environmental_sensor_duty_cycling ,
                        data.environmental_sensor_calibration_date,
                        data.environmental_sensor_calibration_details ,
                        data.physiological_sensor_type ,
                        data.physiological_sensor_manufacturer,
                        data.physiological_sensor_model ,
                        data.physiological_sensor_units_reported ,
                        data.physiological_lower_sensor_detection_limit ,
                        data.physiological_upper_sensor_detection_limit,
                        data.physiological_sensor_precision,
                        data.physiological_sensor_sampling_frequency ,
                        data.physiological_sensor_duty_cycling,
                        data.physiological_sensor_calibration_date,
                        data.physiological_sensor_calibration_details ,
                        data.physiological_sensor_model,
                        data.accelerometry_sensor_manufacturer ,
                        data.accelerometry_sensor_model ,
                        data.accelerometry_sensor_axes,
                        data.accelerometry_sensor_units_reported ,
                        data.accelerometry_lower_sensor_detection_limit ,
                        data.accelerometry_upper_sensor_detection_limit ,
                        data.accelerometry_sensor_precision,
                        data.accelerometry_sensor_sampling_frequency ,
                        data.accelerometry_sensor_duty_cycling ,
                        data.accelerometry_sensor_calibration_date ,
                        data.accelerometry_sensor_calibration_details 
                    ]
                                
    elif csv_type == 'Input Data':
        row_data=([data.instrumentID,data.deploymentID,data.organismID,data.organismIDSource,data.time,data.latitude,
                        data.longitude,data.argosLC,data.argosErrorRadius,
                        data.argosSemiMajor,data.argosSemiMinor,data.argosOrientation,data.argosGDOP,data.gpsSatelliteCount,
                        data.residualsGPS,data.temperatureGLS,data.depthGLS,data.sensorIMeasurement,data.sensor_type])
    return row_data